### ISSUE TITLE
Transform the location of error messages using source maps

### ISSUE THREAD

**Issue by STRd6** [johnie/esbuild-coffeescript#3]
```
coffee build/main.coffee 
X [ERROR] Could not resolve "../pixie"

    lib/exports.coffee:3:21: <- !! This should actually be line 1
      3 │ ({version} = require("../pixie"));
```

The location of error messages comes from the compiled JS, not the CoffeeScript source. It makes jumping to the error slightly annoying.

**Comment by johnie** [comment]
Thanks for your comment! I'll look into it asap 🙏

**Comment by greghuc** [comment]
I've just dug into why error locations from esbuild-coffeescript can be wrong, and was surprised to discover that the coffeescript compiler itself is causing this (at least in my case). If I run my example busted coffeescript file through the coffeescript cli, or the [Coffeescript 'try' page](https://coffeescript.org/#try), I get the same (incorrect) line number and column for the error - which was accurately reported in my esbuild output!
